name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
change-title-escapes: '\<*_&'
exclude-labels:
  - "skip-changelog"
template: |
  ## What’s Changed

  以下を対応。

  ## PR

  $CHANGES
