# ref. https://pre-commit.com/#plugins

fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: check-yaml

  - repo: local
    hooks:
      - id: test-matrix
        name: check test_matrix.yaml
        entry: ./scripts/check_test_matrix.sh
        language: system
        always_run: true

  - repo: local
    hooks:
      - id: terraform-fmt
        name: run terraform fmt
        entry: ./scripts/tffmt.sh
        language: system
        always_run: true

  - repo: local
    hooks:
      - id: tflint
        name: run tflint
        entry: ./scripts/tflint.sh
        language: system
        always_run: true

  # チェックに1分以上かかるのでCIに任せる
  # - repo: local
  #   hooks:
  #     - id: terraform-validate
  #       name: run terraform validate
  #       entry: ./scripts/tfvalidate.sh
  #       language: system
  #       always_run: true
